// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for ios - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAtKaePWJFYF2tuv5_cWEfnu2PLOuFBqQc',
    appId: '1:696502493818:web:f9cc730e7d84350e2211c3',
    messagingSenderId: '696502493818',
    projectId: 'alertatotal-4c9eb',
    authDomain: 'alertatotal-4c9eb.firebaseapp.com',
    storageBucket: 'alertatotal-4c9eb.appspot.com',
    measurementId: 'G-FP4V843BPX',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCMrhs19h9dCnTrcLUNJIHYUjgSnjAmbK4',
    appId: '1:696502493818:android:21a068f25e27d01b2211c3',
    messagingSenderId: '696502493818',
    projectId: 'alertatotal-4c9eb',
    storageBucket: 'alertatotal-4c9eb.appspot.com',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyAtKaePWJFYF2tuv5_cWEfnu2PLOuFBqQc',
    appId: '1:696502493818:web:66fd5c5c0edefdd92211c3',
    messagingSenderId: '696502493818',
    projectId: 'alertatotal-4c9eb',
    authDomain: 'alertatotal-4c9eb.firebaseapp.com',
    storageBucket: 'alertatotal-4c9eb.appspot.com',
    measurementId: 'G-Z0ZMY91GYS',
  );
}
